[package]
name = "vrf-primitives"
authors = [ "PureStake" ]
description = "Primitives for VRF"
edition = "2018"
version = "0.1.0"

[dependencies]
nimbus-primitives = { git = "https://github.com/purestake/nimbus", branch = "moonbeam-polkadot-v0.9.18", default-features = false }

[features]
default = [ "std" ]
std = [
	"nimbus-primitives/std",
]
