[workspace]
exclude = [ "bin/utils/moonkey" ]
members = [
	"bin/utils/moonkey",
	"client/rpc/finality",
	"client/rpc/manual-xcm",
	"node",
	"node/cli",
	"node/service",
	"pallets/maintenance-mode",
	"pallets/migrations",
	"pallets/proxy-genesis-companion",
	"precompiles/utils/macro",
	"precompiles/batch",
	"runtime/moonbase",
	"runtime/moonbeam",
	"runtime/moonriver",
]

[patch.crates-io]
evm = { git = "https://github.com/purestake/evm", branch = "jeremy-precompile-code-35" }
evm-gasometer = { git = "https://github.com/purestake/evm", branch = "jeremy-precompile-code-35" }
evm-runtime = { git = "https://github.com/purestake/evm", branch = "jeremy-precompile-code-35" }

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
inherits = "release"

[profile.production]
codegen-units = 1
incremental = false
inherits = "release"
lto = true

[profile.release]
# Moonbeam runtime requires unwinding.
opt-level = 3
panic = "unwind"
